const ActionType = {
  CHOOSE_CITY: `CHOOSE_CITY`,
  LOAD_DATA: `LOAD_DATA`,
  REQUIRED_AUTHORIZATION: `REQUIRED_AUTHORIZATION`,
  SEND_COMMENTS: `SEND_COMMENTS`,
  LOAD_COMMENTS: `LOAD_COMMENTS`,
  ADD_FAVORITES: `ADD_FAVORITES`,
  LOAD_OFFER: `LOAD_OFFER`,
  LOAD_NEARBY: `LOAD_NEARBY`,
};

export {ActionType};
