"use strict";

window.data = [
  {
    id: 1,
    author: "keks",
    url: "photos/1.jpg",
    description: "Мой первый пост в Keksogram!",
    likes: 42,
    comments: [
      { avatar: "img/avatar-1.svg", message: "Классно!" },
      { avatar: "img/avatar-3.svg", message: "Как мило :3" },
      { avatar: "img/avatar-2.svg", message: "Привет, Кекс!" },
    ],
    hashtags: ["#кот", "#keks"],
  },
  {
    id: 2,
    author: "whiskers",
    url: "photos/2.jpg",
    description: "Солнечный день на подоконнике",
    likes: 35,
    comments: [{ avatar: "img/avatar-2.svg", message: "Прекрасный кадр!" }],
    hashtags: ["#котики", "#солнце"],
  },
  {
    id: 3,
    author: "murzik",
    url: "photos/3.jpg",
    description: "Новая игрушка - лучший подарок",
    likes: 28,
    comments: [
      { avatar: "img/avatar-5.svg", message: "Где купить такую?" },
      { avatar: "img/avatar-1.svg", message: "Мой тоже такую обожает" },
      { avatar: "img/avatar-4.svg", message: "Крутая игрушка!" },
      { avatar: "img/avatar-3.svg", message: "Хочу такую же" },
    ],
    hashtags: ["#игрушки", "#котэ"],
  },
  {
    id: 4,
    author: "barsik",
    url: "photos/4.jpg",
    description: "После вкусного обеда",
    likes: 56,
    comments: [
      { avatar: "img/avatar-3.svg", message: "Выглядит довольным" },
      { avatar: "img/avatar-2.svg", message: "Сладко спит" },
      { avatar: "img/avatar-5.svg", message: "Объелся и доволен" },
    ],
    hashtags: ["#обед", "#сон"],
  },
  {
    id: 5,
    author: "simba",
    url: "photos/5.jpg",
    description: "Исследую новые территории",
    likes: 47,
    comments: [
      { avatar: "img/avatar-4.svg", message: "Храбрый исследователь!" },
      { avatar: "img/avatar-5.svg", message: "Будь осторожен!" },
      { avatar: "img/avatar-1.svg", message: "Куда путь держишь?" },
      { avatar: "img/avatar-2.svg", message: "Открыватель!" },
      { avatar: "img/avatar-3.svg", message: "Новые горизонты" },
    ],
    hashtags: ["#приключения", "#котопутешественник"],
  },
  {
    id: 6,
    author: "luna",
    url: "photos/6.jpg",
    description: "Люблю коробки больше, чем игрушки",
    likes: 63,
    comments: [
      { avatar: "img/avatar-1.svg", message: "Классика!" },
      { avatar: "img/avatar-3.svg", message: "Все коты обожают коробки" },
    ],
    hashtags: ["#коробка", "#уют"],
  },
  {
    id: 7,
    author: "oliver",
    url: "photos/7.jpg",
    description: "Моя любимая игрушка",
    likes: 39,
    comments: [{ avatar: "img/avatar-2.svg", message: "Выглядит изношенной)" }],
    hashtags: ["#игрушка", "#любимое"],
  },
  {
    id: 8,
    author: "chloe",
    url: "photos/8.jpg",
    description: "Утро начинается с кофе... и меня",
    likes: 72,
    comments: [
      { avatar: "img/avatar-5.svg", message: "Идеальное утро!" },
      { avatar: "img/avatar-1.svg", message: "Кот и кофе - лучшее сочетание" },
      { avatar: "img/avatar-3.svg", message: "Бодрое начало дня" },
    ],
    hashtags: ["#утро", "#кофе"],
  },
  {
    id: 9,
    author: "leo",
    url: "photos/9.jpg",
    description: "Задумчивый взгляд в окно",
    likes: 44,
    comments: [
      { avatar: "img/avatar-3.svg", message: "О чем задумался?" },
      { avatar: "img/avatar-2.svg", message: "Философский кот" },
      { avatar: "img/avatar-4.svg", message: "Мечтает о птичках" },
      { avatar: "img/avatar-1.svg", message: "Глубокие мысли" },
    ],
    hashtags: ["#размышления", "#окно"],
  },
  {
    id: 10,
    author: "milo",
    url: "photos/10.jpg",
    description: "Поймал солнечного зайчика",
    likes: 51,
    comments: [{ avatar: "img/avatar-4.svg", message: "Ловкий!" }],
    hashtags: ["#солнце", "#игра"],
  },
  {
    id: 11,
    author: "bella",
    url: "photos/11.jpg",
    description: "Моя королевская поза",
    likes: 68,
    comments: [
      { avatar: "img/avatar-1.svg", message: "Настоящая королева!" },
      { avatar: "img/avatar-3.svg", message: "Величественно!" },
      { avatar: "img/avatar-5.svg", message: "Царственная особа" },
      { avatar: "img/avatar-2.svg", message: "Красотка!" },
      { avatar: "img/avatar-4.svg", message: "Гордая" },
    ],
    hashtags: ["#королева", "#грация"],
  },
  {
    id: 12,
    author: "max",
    url: "photos/12.jpg",
    description: "После долгого дня...",
    likes: 37,
    comments: [{ avatar: "img/avatar-2.svg", message: "Выглядит уставшим" }],
    hashtags: ["#отдых", "#сон"],
  },
  {
    id: 13,
    author: "lily",
    url: "photos/13.jpg",
    description: "Прячусь от дождя",
    likes: 42,
    comments: [
      { avatar: "img/avatar-5.svg", message: "Бедняжка" },
      { avatar: "img/avatar-1.svg", message: "Теплое местечко нашла" },
      { avatar: "img/avatar-3.svg", message: "Не любит дождь" },
    ],
    hashtags: ["#дождь", "#укрытие"],
  },
  {
    id: 14,
    author: "oscar",
    url: "photos/14.jpg",
    description: "Моя добыча",
    likes: 55,
    comments: [
      { avatar: "img/avatar-3.svg", message: "Охотник!" },
      { avatar: "img/avatar-2.svg", message: "Что это было?" },
      { avatar: "img/avatar-4.svg", message: "Настоящий хищник" },
    ],
    hashtags: ["#охота", "#добыча"],
  },
  {
    id: 15,
    author: "sophie",
    url: "photos/15.jpg",
    description: "Люблю когда чешут за ушком",
    likes: 60,
    comments: [{ avatar: "img/avatar-4.svg", message: "Блаженство!" }],
    hashtags: ["#ласка", "#удовольствие"],
  },
  {
    id: 16,
    author: "jack",
    url: "photos/16.jpg",
    description: "Застрял в коробке... снова",
    likes: 48,
    comments: [
      { avatar: "img/avatar-1.svg", message: "Ха-ха, классика!" },
      { avatar: "img/avatar-3.svg", message: "Если влез, то вылезет" },
      { avatar: "img/avatar-5.svg", message: "Помочь тебе?" },
    ],
    hashtags: ["#коробка", "#приключения"],
  },
  {
    id: 17,
    author: "cleo",
    url: "photos/17.jpg",
    description: "Новый головной убор",
    likes: 73,
    comments: [
      { avatar: "img/avatar-2.svg", message: "Стильно!" },
      { avatar: "img/avatar-4.svg", message: "Модница!" },
      { avatar: "img/avatar-1.svg", message: "Где купила?" },
      { avatar: "img/avatar-3.svg", message: "Идет тебе" },
    ],
    hashtags: ["#мода", "#шляпа"],
  },
  {
    id: 18,
    author: "tiger",
    url: "photos/18.jpg",
    description: "Обед по расписанию",
    likes: 41,
    comments: [
      { avatar: "img/avatar-5.svg", message: "Точность - вежливость королей" },
    ],
    hashtags: ["#еда", "#режим"],
  },
  {
    id: 19,
    author: "molly",
    url: "photos/19.jpg",
    description: "Моя любимая лежанка",
    likes: 52,
    comments: [
      { avatar: "img/avatar-3.svg", message: "Уютное местечко" },
      { avatar: "img/avatar-2.svg", message: "Где купить такую?" },
      { avatar: "img/avatar-4.svg", message: "Выглядит комфортно" },
      { avatar: "img/avatar-1.svg", message: "Мечтаю о такой" },
    ],
    hashtags: ["#лежанка", "#комфорт"],
  },
  {
    id: 20,
    author: "simon",
    url: "photos/20.jpg",
    description: "Играем в прятки",
    likes: 45,
    comments: [
      { avatar: "img/avatar-4.svg", message: "Я тебя вижу!" },
      { avatar: "img/avatar-5.svg", message: "Хорошо спрятался" },
      { avatar: "img/avatar-2.svg", message: "Нашел!" },
    ],
    hashtags: ["#игра", "#прятки"],
  },
  {
    id: 21,
    author: "zoe",
    url: "photos/21.jpg",
    description: "Люблю высоту",
    likes: 57,
    comments: [{ avatar: "img/avatar-1.svg", message: "Смелая!" }],
    hashtags: ["#высота", "#баланс"],
  },
  {
    id: 22,
    author: "felix",
    url: "photos/22.jpg",
    description: "Моя дневная дрема",
    likes: 49,
    comments: [
      { avatar: "img/avatar-2.svg", message: "Сладких снов" },
      { avatar: "img/avatar-4.svg", message: "Выглядит умиротворенно" },
      { avatar: "img/avatar-3.svg", message: "Котик спит" },
      { avatar: "img/avatar-5.svg", message: "Спокойного сна" },
    ],
    hashtags: ["#дрема", "#отдых"],
  },
  {
    id: 23,
    author: "lucky",
    url: "photos/23.jpg",
    description: "Поймал хвост!",
    likes: 66,
    comments: [
      { avatar: "img/avatar-5.svg", message: "Поздравляю с победой!" },
      { avatar: "img/avatar-1.svg", message: "Мой все никак не поймает" },
      { avatar: "img/avatar-2.svg", message: "Ловкость!" },
    ],
    hashtags: ["#хвост", "#игра"],
  },
  {
    id: 24,
    author: "ginger",
    url: "photos/24.jpg",
    description: "Моя любимая игрушка - плюшевый мишка",
    likes: 53,
    comments: [{ avatar: "img/avatar-3.svg", message: "Такой милый!" }],
    hashtags: ["#игрушка", "#друг"],
  },
  {
    id: 25,
    author: "shadow",
    url: "photos/25.jpg",
    description: "Спрятался в самом неожиданном месте",
    likes: 59,
    comments: [
      { avatar: "img/avatar-4.svg", message: "Мастер камуфляжа!" },
      { avatar: "img/avatar-5.svg", message: "Еле нашла!" },
      { avatar: "img/avatar-1.svg", message: "Где ты?" },
      { avatar: "img/avatar-2.svg", message: "Отличная маскировка" },
      { avatar: "img/avatar-3.svg", message: "Невидимка" },
    ],
    hashtags: ["#прятки", "#тайник"],
  },
];
